include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint

linter:
  rules:
    constant_identifier_names: false
    non_constant_identifier_names: false
    prefer_relative_imports: true
    directives_ordering: true
    no_leading_underscores_for_local_identifiers: false
